/* Generated By:JJTree: Do not edit this line. ASTBitwiseAndExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBitwiseAndExpression extends SimpleNode {
  public ASTBitwiseAndExpression(int id) {
    super(id);
  }

  public ASTBitwiseAndExpression(PHP p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(PHPVisitor visitor, Object data) {

    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e333d275a85268897454308f82c56f9f (do not edit this line) */
