/* Generated By:JJTree: Do not edit this line. ASTClassMembers.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTClassMembers extends SimpleNode {
  public ASTClassMembers(int id) {
    super(id);
  }

  public ASTClassMembers(PHP p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(PHPVisitor visitor, Object data) {

    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0c2ae316cadb111565c1274fb726020a (do not edit this line) */
