/* Generated By:JJTree: Do not edit this line. ASTClassInstantiation.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTClassInstantiation extends SimpleNode {
  public ASTClassInstantiation(int id) {
    super(id);
  }

  public ASTClassInstantiation(PHP p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(PHPVisitor visitor, int branchAdd) {

    visitor.visit(this, branchAdd);
  }
}
/* JavaCC - OriginalChecksum=53268cac97d5b3abf7099df894ed1254 (do not edit this line) */
