/* Generated By:JJTree: Do not edit this line. ASTDefineStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDefineStatement extends SimpleNode {
  public ASTDefineStatement(int id) {
    super(id);
  }

  public ASTDefineStatement(PHP p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(PHPVisitor visitor, Object data) {

    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8c23ad89a29a3e0c88cb81191dc63481 (do not edit this line) */
