/* Generated By:JJTree: Do not edit this line. ASTDoubleStringLiteral.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDoubleStringLiteral extends SimpleNode {
  public ASTDoubleStringLiteral(int id) {
    super(id);
  }

  public ASTDoubleStringLiteral(PHP p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(PHPVisitor visitor, Object data) {

    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=21899662c2a3f78d1af835c19b2c468f (do not edit this line) */
