/* Generated By:JJTree: Do not edit this line. ASTEmbeddedHtml.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEmbeddedHtml extends SimpleNode {
  public ASTEmbeddedHtml(int id) {
    super(id);
  }

  public ASTEmbeddedHtml(PHP p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(PHPVisitor visitor, int branchAdd) {

    visitor.visit(this, branchAdd);
  }
}
/* JavaCC - OriginalChecksum=3fd2a6fdcb77444e672910c1977322ed (do not edit this line) */
