/* Generated By:JJTree: Do not edit this line. ASTEchoStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEchoStatement extends SimpleNode {
  public ASTEchoStatement(int id) {
    super(id);
  }

  public ASTEchoStatement(PHP p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(PHPVisitor visitor, Object data) {

    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8dd4611dcf15a3bd82fcc74b748e0520 (do not edit this line) */
