/* Generated By:JJTree: Do not edit this line. ASTEndOfStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTEndOfStatement extends SimpleNode {
  public ASTEndOfStatement(int id) {
    super(id);
  }

  public ASTEndOfStatement(PHP p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(PHPVisitor visitor, int branchAdd) {

    visitor.visit(this, branchAdd);
  }
}
/* JavaCC - OriginalChecksum=10b739dd3149c6ac9d8eb5f46a7d32f7 (do not edit this line) */
