/* Generated By:JJTree: Do not edit this line. ASTHtmlBlock.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTHtmlBlock extends SimpleNode {
  public ASTHtmlBlock(int id) {
    super(id);
  }

  public ASTHtmlBlock(PHP p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(PHPVisitor visitor, Object data) {

    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e46eb804ece9a722f9215aba591c063a (do not edit this line) */
