/* Generated By:JJTree: Do not edit this line. ASTInterfaceMember.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTInterfaceMember extends SimpleNode {
  public ASTInterfaceMember(int id) {
    super(id);
  }

  public ASTInterfaceMember(PHP p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(PHPVisitor visitor, int branchAdd) {

    visitor.visit(this, branchAdd);
  }
}
/* JavaCC - OriginalChecksum=08987a8b18a8e26b846d292db0b1b839 (do not edit this line) */
