/* Generated By:JJTree: Do not edit this line. ASTInstanceOfExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTInstanceOfExpression extends SimpleNode {
  public ASTInstanceOfExpression(int id) {
    super(id);
  }

  public ASTInstanceOfExpression(PHP p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(PHPVisitor visitor, int branchAdd) {

    visitor.visit(this, branchAdd);
  }
}
/* JavaCC - OriginalChecksum=1762a77e361976470a5770e6cf0a8e82 (do not edit this line) */
