/* Generated By:JJTree: Do not edit this line. ASTIncludeStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIncludeStatement extends SimpleNode {
  public ASTIncludeStatement(int id) {
    super(id);
  }

  public ASTIncludeStatement(PHP p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(PHPVisitor visitor, int branchAdd) {

    visitor.visit(this, branchAdd);
  }
}
/* JavaCC - OriginalChecksum=693cb0499c6e9291530b8cb00c360b72 (do not edit this line) */
