/* Generated By:JJTree: Do not edit this line. ASTIterationStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIterationStatement extends SimpleNode {
  public ASTIterationStatement(int id) {
    super(id);
  }

  public ASTIterationStatement(PHP p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(PHPVisitor visitor, Object data) {

    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=75f148fb7e8f6b031a3987237befd7ee (do not edit this line) */
