/* Generated By:JJTree: Do not edit this line. ASTJumpStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTJumpStatement extends SimpleNode {
  public ASTJumpStatement(int id) {
    super(id);
  }

  public ASTJumpStatement(PHP p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(PHPVisitor visitor, int branchAdd) {

    visitor.visit(this, branchAdd);
  }
}
/* JavaCC - OriginalChecksum=6afe0f819ab113dcffb30438619fcbe8 (do not edit this line) */
