/* Generated By:JJTree: Do not edit this line. ASTLogicalTextAndExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLogicalTextAndExpression extends SimpleNode {
  public ASTLogicalTextAndExpression(int id) {
    super(id);
  }

  public ASTLogicalTextAndExpression(PHP p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(PHPVisitor visitor, Object data) {

    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=72bc47aec90c4b7c25585d8deceb5ee7 (do not edit this line) */
