/* Generated By:JJTree: Do not edit this line. ASTLogicalTextXorExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLogicalTextXorExpression extends SimpleNode {
  public ASTLogicalTextXorExpression(int id) {
    super(id);
  }

  public ASTLogicalTextXorExpression(PHP p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(PHPVisitor visitor, Object data) {

    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a72ba8320e421f85e1e7ef60a9b3112c (do not edit this line) */
