/* Generated By:JJTree: Do not edit this line. ASTLogical_And_Expression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLogical_And_Expression extends SimpleNode {
  public ASTLogical_And_Expression(int id) {
    super(id);
  }

  public ASTLogical_And_Expression(PHP p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(PHPVisitor visitor, Object data) {

    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5ba6b7ef7479ba666a10b8d99db6bbca (do not edit this line) */
