/* Generated By:JJTree: Do not edit this line. ASTLogical_Or_Expression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLogical_Or_Expression extends SimpleNode {
  public ASTLogical_Or_Expression(int id) {
    super(id);
  }

  public ASTLogical_Or_Expression(PHP p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(PHPVisitor visitor, Object data) {

    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d2fec4ee4de88645c05c9a76d1a6b94a (do not edit this line) */
