/* Generated By:JJTree: Do not edit this line. ASTPrefixIncDecExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPrefixIncDecExpression extends SimpleNode {
  public ASTPrefixIncDecExpression(int id) {
    super(id);
  }

  public ASTPrefixIncDecExpression(PHP p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(PHPVisitor visitor, Object data) {

    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b3e3a2d8f38eb560a7d6f29ec6478ef3 (do not edit this line) */
