/* Generated By:JJTree: Do not edit this line. ASTVisibility.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVisibility extends SimpleNode {
  public ASTVisibility(int id) {
    super(id);
  }

  public ASTVisibility(PHP p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public void jjtAccept(PHPVisitor visitor, Object data) {

    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cc42d778e8d1a28cfa6c90d1f6a2d7df (do not edit this line) */
